development:
  adapter: postgresql
  encoding: unicode
  database: resolutions_development
  pool: 5
  username: pgdev
  password: pgdevpw
test:
  adapter: postgresql
  encoding: unicode
  database: resolutions_test
  pool: 5
  username: pgdev
  password: pgdevpw
production:
  adapter: postgresql
  encoding: unicode
  database: resolutions_production
  pool: 5
  username: myapp
  password:
